//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.0
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Charlie.Web.WordPress.Data.DataResources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DispayResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DispayResource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Charlie.Web.WordPress.Data.DataResources.DispayResource", typeof(DispayResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Post_Content_Description 的本地化字符串。
        /// </summary>
        public static string Post_Content_Description {
            get {
                return ResourceManager.GetString("Post_Content_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Post_Content_Name 的本地化字符串。
        /// </summary>
        public static string Post_Content_Name {
            get {
                return ResourceManager.GetString("Post_Content_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Post_Content_Prompt 的本地化字符串。
        /// </summary>
        public static string Post_Content_Prompt {
            get {
                return ResourceManager.GetString("Post_Content_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Post_Id_Description 的本地化字符串。
        /// </summary>
        public static string Post_Id_Description {
            get {
                return ResourceManager.GetString("Post_Id_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Post_Id_Name 的本地化字符串。
        /// </summary>
        public static string Post_Id_Name {
            get {
                return ResourceManager.GetString("Post_Id_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Post_Id_Prompt 的本地化字符串。
        /// </summary>
        public static string Post_Id_Prompt {
            get {
                return ResourceManager.GetString("Post_Id_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Post_Keywords_Description 的本地化字符串。
        /// </summary>
        public static string Post_Keywords_Description {
            get {
                return ResourceManager.GetString("Post_Keywords_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Post_Keywords_Name 的本地化字符串。
        /// </summary>
        public static string Post_Keywords_Name {
            get {
                return ResourceManager.GetString("Post_Keywords_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Post_Keywords_Prompt 的本地化字符串。
        /// </summary>
        public static string Post_Keywords_Prompt {
            get {
                return ResourceManager.GetString("Post_Keywords_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Post_Name_Description 的本地化字符串。
        /// </summary>
        public static string Post_Name_Description {
            get {
                return ResourceManager.GetString("Post_Name_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Post_Name_Name 的本地化字符串。
        /// </summary>
        public static string Post_Name_Name {
            get {
                return ResourceManager.GetString("Post_Name_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Post_Name_Prompt 的本地化字符串。
        /// </summary>
        public static string Post_Name_Prompt {
            get {
                return ResourceManager.GetString("Post_Name_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Post_Publish_Description 的本地化字符串。
        /// </summary>
        public static string Post_Publish_Description {
            get {
                return ResourceManager.GetString("Post_Publish_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Post_Publish_Name 的本地化字符串。
        /// </summary>
        public static string Post_Publish_Name {
            get {
                return ResourceManager.GetString("Post_Publish_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Post_Publish_Prompt 的本地化字符串。
        /// </summary>
        public static string Post_Publish_Prompt {
            get {
                return ResourceManager.GetString("Post_Publish_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Post_Status_Description 的本地化字符串。
        /// </summary>
        public static string Post_Status_Description {
            get {
                return ResourceManager.GetString("Post_Status_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Post_Status_Name 的本地化字符串。
        /// </summary>
        public static string Post_Status_Name {
            get {
                return ResourceManager.GetString("Post_Status_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Post_Status_Prompt 的本地化字符串。
        /// </summary>
        public static string Post_Status_Prompt {
            get {
                return ResourceManager.GetString("Post_Status_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Post_Summary_Description 的本地化字符串。
        /// </summary>
        public static string Post_Summary_Description {
            get {
                return ResourceManager.GetString("Post_Summary_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Post_Summary_Name 的本地化字符串。
        /// </summary>
        public static string Post_Summary_Name {
            get {
                return ResourceManager.GetString("Post_Summary_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Post_Summary_Prompt 的本地化字符串。
        /// </summary>
        public static string Post_Summary_Prompt {
            get {
                return ResourceManager.GetString("Post_Summary_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Post_Title_Description 的本地化字符串。
        /// </summary>
        public static string Post_Title_Description {
            get {
                return ResourceManager.GetString("Post_Title_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Post_Title_Name 的本地化字符串。
        /// </summary>
        public static string Post_Title_Name {
            get {
                return ResourceManager.GetString("Post_Title_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Post_Title_Prompt 的本地化字符串。
        /// </summary>
        public static string Post_Title_Prompt {
            get {
                return ResourceManager.GetString("Post_Title_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Post_UserId_Description 的本地化字符串。
        /// </summary>
        public static string Post_UserId_Description {
            get {
                return ResourceManager.GetString("Post_UserId_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Post_UserId_Name 的本地化字符串。
        /// </summary>
        public static string Post_UserId_Name {
            get {
                return ResourceManager.GetString("Post_UserId_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Post_UserId_Prompt 的本地化字符串。
        /// </summary>
        public static string Post_UserId_Prompt {
            get {
                return ResourceManager.GetString("Post_UserId_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Post_VirtualPath_Description 的本地化字符串。
        /// </summary>
        public static string Post_VirtualPath_Description {
            get {
                return ResourceManager.GetString("Post_VirtualPath_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Post_VirtualPath_Name 的本地化字符串。
        /// </summary>
        public static string Post_VirtualPath_Name {
            get {
                return ResourceManager.GetString("Post_VirtualPath_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Post_VirtualPath_Prompt 的本地化字符串。
        /// </summary>
        public static string Post_VirtualPath_Prompt {
            get {
                return ResourceManager.GetString("Post_VirtualPath_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Post_VirtualPathHash_Description 的本地化字符串。
        /// </summary>
        public static string Post_VirtualPathHash_Description {
            get {
                return ResourceManager.GetString("Post_VirtualPathHash_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Post_VirtualPathHash_Name 的本地化字符串。
        /// </summary>
        public static string Post_VirtualPathHash_Name {
            get {
                return ResourceManager.GetString("Post_VirtualPathHash_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Post_VirtualPathHash_Prompt 的本地化字符串。
        /// </summary>
        public static string Post_VirtualPathHash_Prompt {
            get {
                return ResourceManager.GetString("Post_VirtualPathHash_Prompt", resourceCulture);
            }
        }
    }
}
